spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create          # Only in developing stage!
    properties:
      hibernate:
        #show_sql: true         # print in console -> use hibernate.SQL
        format_sql: true

logging.level:
    org.hibernate.SQL: debug    # leave as a log
    #org.hibernate.type: trace  # To check parameter # It's better to use p6spy library.